---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: development
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: development
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
